[package]
name = "rubiks-api"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.4", features = ["json"] }
tokio = { version = "1.47.1", features = ["macros", "rt-multi-thread"] }
rubiks = { path = "../rubiks" }
